Repository kroshu/kuka_drivers, pull requests merged in 2025-08, with the labels that each got.

#248 Handle Failed Motion State Reception
  kuka_rsi_driver/src/hardware_interface_eki_rsi.cpp
Labels: bug

#246 Solve warning on master for release
  controllers/fri_state_broadcaster/src/fri_state_broadcaster.cpp
  controllers/joint_group_impedance_controller/include/joint_group_impedance_controller/joint_group_impedance_controller.hpp
  controllers/kuka_control_mode_handler/include/kuka_control_mode_handler/kuka_control_mode_handler.hpp
  controllers/kuka_control_mode_handler/src/kuka_control_mode_handler.cpp
  controllers/kuka_event_broadcaster/src/kuka_event_broadcaster.cpp
  examples/iiqka_moveit_example/include/iiqka_moveit_example/moveit_example.hpp
  kuka_iiqka_eac_driver/src/robot_manager_node.cpp
  kuka_sunrise_fri_driver/CMakeLists.txt
  kuka_sunrise_fri_driver/src/robot_manager_node.cpp
Labels: bug

#251 Add tested setups for different drivers
  doc/wiki/1_iiQKA_EAC.md
  doc/wiki/2_KSS_RSI.md
  doc/wiki/3_iiQKA.OS2_RSI.md
Labels: documentation, jazzy

#252 Add tested setups for different drivers (Backport #251)
  controllers/joint_group_impedance_controller/include/joint_group_impedance_controller/joint_group_impedance_controller.hpp
  doc/wiki/1_iiQKA_EAC.md
  doc/wiki/2_KSS_RSI.md
  doc/wiki/3_iiQKA.OS2_RSI.md
Labels: documentation, backport-humble
